##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Copyright © dev-cetera.com & contributors.
##
## The use of this source code is governed by an MIT-style license described in
## the LICENSE file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: generate_dart_indexes
homepage: https://dev-cetera.com/
funding:
- https://www.buymeacoffee.com/dev_cetera
- https://www.patreon.com/c/robelator
- https://github.com/sponsors/robelator
- https://www.patreon.com/c/robelator
- https://github.com/sponsors/robelator
- https://www.buymeacoffee.com/dev_cetera


publish_to: none

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  df_generate_dart_indexes:
    path: ../

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^6.0.0

